import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.kingbillycasino.com/")
    page.get_by_role("button", name="accept").click()
    page.get_by_role("link", name="sign in").click()
    page.get_by_placeholder("your e-mail address").fill("")
    page.get_by_placeholder("your e-mail address").click()
    page.get_by_placeholder("your e-mail address").fill("\"mike0@kingbilly.xyz")
    page.get_by_placeholder("your password").click()
    page.get_by_placeholder("your password").fill("LOL12lol!")
    page.get_by_placeholder("your e-mail address").click()
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowLeft")
    page.get_by_placeholder("your e-mail address").press("ArrowRight")
    page.get_by_placeholder("your e-mail address").fill("mike0@kingbilly.xyz")
    page.get_by_role("button", name="sign in").click()
    page.get_by_text("Direct BankingDirectMifinityCoinspaidALLE METHODEN SEHENEINZAHLEN & SPIELEN").click()
    page.get_by_text("Suchen Sie Ihre SpieleSuchen Sie Ihre SpieleShow more0EURKeine aktuelle").click()
    page.get_by_role("banner").get_by_role("link").first.click()
    page.locator("button:nth-child(3)").first.click()
    page.locator("button:nth-child(3)").first.click()
    page.locator("button:nth-child(3)").first.click()
    page.locator("button:nth-child(3)").first.click()
    page.locator("button:nth-child(3)").first.click()
    page.locator("div").filter(has_text="Bonimehr anzeigenStimmen Sie").nth(3).click()
    page.get_by_role("banner").get_by_role("img", name="de").click()
    page.get_by_role("option", name="en en").click()
    page.locator("div").filter(has_text="PromotionsShow moreVote for").nth(3).click()
    page.get_by_role("heading", name="Promotions").click()
    page.locator("div").filter(has_text="PromotionsShow moreVote for").nth(3).click()
    page.locator(".promos-slider > .slick-slider > button:nth-child(3)").click()
    page.locator(".promos-slider > .slick-slider > button:nth-child(3)").click()
    page.locator(".promos-slider > .slick-slider > button:nth-child(3)").click()
    page.locator(".promos-slider > .slick-slider > button:nth-child(3)").click()
    page.get_by_role("banner").get_by_role("button").first.click()
    page.locator("#bar").get_by_role("link", name="Promotions").click()
    page.locator(".header__bar").click()
    page.locator("#bar").get_by_role("link", name="Tournaments").click()
    page.locator(".slick-slider").first.click()
    page.get_by_role("main").get_by_role("button", name="").click()
    page.get_by_role("main").get_by_role("button", name="").click()
    page.get_by_role("main").get_by_role("button", name="").click()
    page.get_by_role("main").get_by_role("button", name="").dblclick()
    page.get_by_role("main").get_by_role("button", name="").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)